
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: echo "Its work?"

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: |
          echo "pass secret enable. So username is" $username 
          echo "what is circle_pr_number --> " $CIRCLE_PR_NUMBER
          if [ $CIRCLE_PR_NUMBER ];then
            echo "pr number is exist"
          fi
  second_step:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: |
          echo "This is second step"
          echo "what is circle_pr_number --> " $CIRCLE_PR_NUMBER
          if [ $CIRCLE_PR_NUMBER ];then
            echo "pr number is exist"
          fi

workflows:
  dev_deploy:
    jobs:
      - build
  prod_deploy:
    jobs:
      - second_step

