
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: |
          if [ ! -z $CIRCLE_PR_NUMBER ];then
            echo "pass secret enable. So username is" $username
            echo "what is circle_pr_number --> " $CIRCLE_PR_NUMBER
          fi

  second_step:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - run: |
          echo "what is circle_pr_number --> " $CIRCLE_PR_NUMBER
          echo "This is second step"

workflows:
  dev_deploy:
    jobs:
      - build
  prod_deploy:
    jobs:
      - second_step:
          filters:
            branches:
              only: master
